version: '3'
services:
  db:
    image: postgres
    platform: linux/amd64
    volumes:
      - ./volume_postgres:/var/lib/postgresql/data
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: 
      - "5433:5432"
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - ./volume_pgadmin:/var/lib/pgadmin
    environment:
      TZ: Asia/Tokyo
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/Hokuriku-shien-Travelers-map
    environment:
      TZ: Asia/Tokyo
    ports:
      - "3000:3000"
    depends_on:
      - db